on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        default: false
      ref:
        required: false
        type: string

env:
  IMAGE_NAME: ghcr.io/flyinpancake/book-club-vote

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - uses: docker/metadata-action@v6
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
